# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 895)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-10, 780, 1121, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(16, 0, 16, 0)
        self.horizontalLayout.setSpacing(28)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout.addWidget(self.reset_button)
        self.stop_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.stop_button.setObjectName("stop_button")
        self.horizontalLayout.addWidget(self.stop_button)
        self.down_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.down_button.setObjectName("down_button")
        self.horizontalLayout.addWidget(self.down_button)
        self.up_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.up_button.setObjectName("up_button")
        self.horizontalLayout.addWidget(self.up_button)
        self.earth = QtWidgets.QPushButton(self.centralwidget)
        self.earth.setGeometry(QtCore.QRect(677, 387, 26, 26))
        self.earth.setStyleSheet("border-radius: 13px; \n"
"background-color: rgb(0, 0, 255);")
        self.earth.setText("")
        self.earth.setIconSize(QtCore.QSize(16, 16))
        self.earth.setObjectName("earth")
        self.mercury = QtWidgets.QPushButton(self.centralwidget)
        self.mercury.setGeometry(QtCore.QRect(612, 392, 16, 16))
        self.mercury.setStyleSheet("border-radius: 8px; \n"
"background-color: rgb(255, 55, 37);\n"
"")
        self.mercury.setText("")
        self.mercury.setObjectName("mercury")
        self.venerus = QtWidgets.QPushButton(self.centralwidget)
        self.venerus.setGeometry(QtCore.QRect(645, 390, 20, 20))
        self.venerus.setStyleSheet("border-radius: 10px; \n"
"background-color: rgb(255, 231, 97);")
        self.venerus.setText("")
        self.venerus.setObjectName("venerus")
        self.mars = QtWidgets.QPushButton(self.centralwidget)
        self.mars.setGeometry(QtCore.QRect(715, 390, 20, 20))
        self.mars.setStyleSheet("border-radius: 10px; \n"
"background-color: rgb(255, 12, 12);")
        self.mars.setText("")
        self.mars.setIconSize(QtCore.QSize(16, 16))
        self.mars.setObjectName("mars")
        self.jupiter = QtWidgets.QPushButton(self.centralwidget)
        self.jupiter.setGeometry(QtCore.QRect(743, 383, 34, 34))
        self.jupiter.setStyleSheet("border-radius: 17px; \n"
"background-color: rgb(170, 106, 2);")
        self.jupiter.setText("")
        self.jupiter.setIconSize(QtCore.QSize(16, 16))
        self.jupiter.setObjectName("jupiter")
        self.saturn = QtWidgets.QPushButton(self.centralwidget)
        self.saturn.setGeometry(QtCore.QRect(779, 384, 32, 32))
        self.saturn.setStyleSheet("border-radius: 16px; \n"
"background-color: rgb(255, 170, 0);")
        self.saturn.setText("")
        self.saturn.setIconSize(QtCore.QSize(16, 16))
        self.saturn.setObjectName("saturn")
        self.uran = QtWidgets.QPushButton(self.centralwidget)
        self.uran.setGeometry(QtCore.QRect(815, 385, 30, 30))
        self.uran.setStyleSheet("border-radius: 15px; \n"
"background-color: rgb(0, 170, 255);")
        self.uran.setText("")
        self.uran.setIconSize(QtCore.QSize(16, 16))
        self.uran.setObjectName("uran")
        self.neptun = QtWidgets.QPushButton(self.centralwidget)
        self.neptun.setGeometry(QtCore.QRect(851, 386, 28, 28))
        self.neptun.setStyleSheet("border-radius: 14px; \n"
"background-color: rgb(0, 85, 255);")
        self.neptun.setText("")
        self.neptun.setIconSize(QtCore.QSize(16, 16))
        self.neptun.setObjectName("neptun")
        self.pluton = QtWidgets.QPushButton(self.centralwidget)
        self.pluton.setGeometry(QtCore.QRect(894, 394, 12, 12))
        self.pluton.setStyleSheet("border-radius: 6px; \n"
"background-color: rgb(164, 170, 156);")
        self.pluton.setText("")
        self.pluton.setObjectName("pluton")
        self.sun = QtWidgets.QPushButton(self.centralwidget)
        self.sun.setGeometry(QtCore.QRect(540, 370, 60, 60))
        self.sun.setStyleSheet("border-radius: 30px; \n"
"background-color: rgb(255, 255, 0);")
        self.sun.setText("")
        self.sun.setIconSize(QtCore.QSize(16, 16))
        self.sun.setObjectName("sun")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Модель Солнечной Системы"))
        self.reset_button.setText(_translate("MainWindow", "СБРОС"))
        self.stop_button.setText(_translate("MainWindow", "СТОП"))
        self.down_button.setText(_translate("MainWindow", "НАЗАД"))
        self.up_button.setText(_translate("MainWindow", "ВПЕРЁД"))
