from PyQt5 import QtCore, QtWidgets


class Ui_SolarObjectInfo(object):
    def setupUi(self, SolarObjectInfo):
        SolarObjectInfo.setObjectName("SolarObjectInfo")
        SolarObjectInfo.resize(985, 651)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SolarObjectInfo.sizePolicy().hasHeightForWidth())
        SolarObjectInfo.setSizePolicy(sizePolicy)
        SolarObjectInfo.setWindowTitle("")
        self.img = QtWidgets.QLabel(SolarObjectInfo)
        self.img.setGeometry(QtCore.QRect(19, 60, 361, 360))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img.sizePolicy().hasHeightForWidth())
        self.img.setSizePolicy(sizePolicy)
        self.img.setText("")
        self.img.setObjectName("img")
        self.verticalLayoutWidget = QtWidgets.QWidget(SolarObjectInfo)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(410, 20, 561, 411))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(24)
        self.verticalLayout.setObjectName("verticalLayout")
        self.solar_object_name = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.solar_object_name.sizePolicy().hasHeightForWidth())
        self.solar_object_name.setSizePolicy(sizePolicy)
        self.solar_object_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.solar_object_name.setStyleSheet("font: 75 42pt \"Times New Roman\";")
        self.solar_object_name.setAlignment(QtCore.Qt.AlignCenter)
        self.solar_object_name.setObjectName("solar_object_name")
        self.verticalLayout.addWidget(self.solar_object_name)
        self.main_info = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_info.sizePolicy().hasHeightForWidth())
        self.main_info.setSizePolicy(sizePolicy)
        self.main_info.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.main_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.main_info.setObjectName("main_info")
        self.verticalLayout.addWidget(self.main_info)
        self.other_info = QtWidgets.QLabel(SolarObjectInfo)
        self.other_info.setGeometry(QtCore.QRect(16, 452, 951, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.other_info.sizePolicy().hasHeightForWidth())
        self.other_info.setSizePolicy(sizePolicy)
        self.other_info.setStyleSheet("font: 12pt \"Times New Roman\";")
        self.other_info.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.other_info.setObjectName("other_info")

        self.retranslateUi(SolarObjectInfo)
        QtCore.QMetaObject.connectSlotsByName(SolarObjectInfo)

    def retranslateUi(self, SolarObjectInfo):
        _translate = QtCore.QCoreApplication.translate
        self.solar_object_name.setText(_translate("SolarObjectInfo", "G"))
        self.main_info.setText(_translate("SolarObjectInfo", "d"))
        self.other_info.setText(_translate("SolarObjectInfo", "TextLabel"))
